### ISSUE TITLE
[Feature Request] Sliding animations for workspace switches.

### ISSUE THREAD

**Issue by Animeshz** [yshui/picom#635] opened 2021-06-08 04:46 UTC
Any implementation for top-bottom bottom-top or left-right right-left sliding transition animations for switching desktops/workspaces?

**Comment by subnut** [comment] 2021-06-08 05:35
I guess that's the task of the Window Manager?

I could be wrong, though.

**Comment by OliverLew** [comment] 2021-07-25 03:27
I had the same FR in one of the forks: https://github.com/jonaburg/picom/issues/31. Some are interested, but nobody seems to have actually implemented anything. There might be useful information in that issue, tho.

**Comment by Animeshz** [comment] 2021-10-17 11:36
@pijulius any chance you'll (send a PR and) merge it to the upstream? I see too many fork and hard to work with each one for different features :p its definitely like DWM (building everything by patching the upstream).

**Comment by pijulius** [comment] 2021-10-17 13:01
There is a pull request already here
https://github.com/dccsillag/picom/pull/22

but it's up to Daniel to accept the changes and then it will be up to the moderators here to accept it to picom. Unfortunately don't see much chance for that at the moment as still a lot of these things are in very early state, haven't been tested in all situations so even if it gets into the original picom it will be under a testing branch of some sort I imagine.

**Comment by nonetrix** [comment] 2022-07-24 03:32
Hyprland has this if you can run Wayland well and don't mind Waylands missing features only reason I don't use it is NVIDIA

**Comment by fdev31** [comment] 2023-03-07 21:06
I made some experiments based on the FTLabs branch, trying to keep it generic and up-to-date (but only tested on qtile)...

https://github.com/fdev31/picom

I'm still testing the sliding animation, once I don't see anything I can fix I'll clean up the code and make it optional. Other animations are mostly from FTLabs but I reworked it to be simpler & I believe a bit more generic.

**Comment by absolutelynothelix** [comment] 2023-09-02 12:36
closing as duplicate of #1121.

**Closed by absolutelynothelix** 2023-09-02 12:36 UTC
Labels: duplicate
