### ISSUE TITLE
Using multipass blur, reported

### ISSUE THREAD

**Issue by ckissane** [yshui/picom#294] opened 2020-01-10 20:13 UTC
Using multipass blur, reported,

Also Kawase blur would be cool to have!

**Comment by yshui** [comment] 2020-01-17 14:32
Noted, thanks!

@tryone144 seems to be working on Kawase blur, see #32

**Comment by yshui** [comment] 2020-01-17 14:34
Duplicate of #260

**Closed by yshui** 2020-01-17 14:34 UTC
