### ISSUE TITLE
Fading doesn't affect window decorators.

### ISSUE THREAD

**Issue by pushqrdx** [yshui/picom#63] opened 2018-12-06 13:34 UTC
### Platform
Fedora 29

### GPU, drivers, and screen setup
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: Fedora Project X.org 1.20.3 driver: modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Haswell Desktop v: 4.5 Mesa 18.2.4

### Environment
XFCE 4.12

### Compton version
Latest. Compiled from next branch.

### Compton configuration:
```
# Shadow
shadow = true;
shadow-opacity = 0.5;
shadow-radius = 5;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-exclude = [
 "n:e:Notification",
 "n:e:Docky",
 "g:e:Synapse",
 "g:e:Conky",
 "n:w:*Firefox*",
 "n:w:*Chromium*",
 "n:w:*dockbarx*",
 "class_g ?= 'Cairo-dock'",
 "class_g ?= 'Xfce4-notifyd'",
 "class_g ?= 'Xfce4-power-manager'",
 "class_g ?= 'Notify-osd'",
 "_GTK_FRAME_EXTENTS@:c"
];
no-dock-shadow = true;
no-dnd-shadow = true; 

# Fading
fading = true;
# fade-delta = 30;
fade-in-step = 0.15;
fade-out-step = 0.15;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
fade-exclude = [ ];

# Other
backend = "glx";
vsync = "opengl";

# OpenGL
glx-no-stencil = true;
glx-swap-method = "-1";
# xrender-sync = true;
# xrender-sync-fence = true;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.90; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.95; }
  dropdown_menu = { opacity = 0.95; }
};
```

### Steps of reproduction
With fading enabled start, close or minimize, unminimize windows (borders will always appear before actual window content)

### Expected behavior
All window content nicely fading either in or out.

### Current Behavior
Window decorator isn't affected by fading.

**Comment by pushqrdx** [comment] 2018-12-07 16:40
@yshui after reading the issue I don't think they'r related.. _maybe i am mistaken_

**Comment by ncmprhnsbl** [comment] 2018-12-08 06:16
well, i don't think i'm seeing this in openbox (with compton  v4)
tested with fade-in-step = 0.01;

**Comment by pushqrdx** [comment] 2018-12-16 22:35
@yshui The issue was with the latest `next` branch. Simply minimizing, unminimizing or opening new windows have their borders appear first before the actual window content itself. The issue appears if you have fading. Try setting a longer fading duration.

**Comment by yshui** [comment] 2018-12-17 01:07
@pushqrdx Interesting, I can reproduce it now, but only during fade out, and not reliably.

I will look into this.

**Comment by yshui** [comment] 2018-12-17 22:07
@pushqrdx The direct cause seems to be that the body of the window disappeared from the pixmap when it is unmapped. Maybe xfwm4 is doing something that clears the body of window when it is unmapped.

**Comment by yshui** [comment] 2018-12-17 22:08
There is _probably_ no much we can do.

I will look a bit more into this

**Comment by pushqrdx** [comment] 2018-12-19 02:41
@yshui yeah I am pretty sure it happened regardless of backend used

**Comment by yshui** [comment] 2018-12-19 14:11
Observation: I can only reproduce this during fading out of some opengl windows (my example is alacritty).

**Comment by yshui** [comment] 2018-12-19 20:06
@pushqrdx I think this is somewhat related to how xfwm4 does thing. Could you also raise this issue to XFCE? They might have more information on this.

**Comment by pushqrdx** [comment] 2019-01-19 15:38
@yshui Sorry for the delayed response, No i didn't as i thought it's compositor related.

**Comment by yshui** [comment] 2019-01-19 16:48
@pushqrdx OK, I will do it myself then.

**Comment by yshui** [comment] 2019-04-25 22:06
A fix seems to have been pushed upstream: https://git.xfce.org/xfce/xfwm4/commit?id=63a797b13023394937a89b41708e40d11b8fa5b2

Can you test and confirm if it works? @pushqrdx

**Comment by pushqrdx** [comment] 2019-05-07 13:18
i am sorry for the late reply but it's kinda hard for me to confirm that at the moment (away from my setup), i'll try my best to confirm as soon as possible though.

**Comment by yshui** [comment] 2024-02-07 10:19
closing as this is not a picom bug, and should have been fixed in xfce upstream (though reporter hasn't confirmed).

**Closed by yshui** 2024-02-07 10:19 UTC
Labels: bug, artifacts, info requested, wm/de
