### ISSUE TITLE
How to remove frame from such types of menus-windows

### ISSUE THREAD

**Issue by Ygarr** [yshui/picom#572] opened 2020-12-18 20:11 UTC
### Platform
Manjaro 20.2 Nibia
### GPU, drivers, and screen setup
integrated Intel Haswell-ULT 

### Environment
Mate
### picom version
picom --version
vgit-af991

### Configuration:

`// Paste your configuration here`
```
cat ~/.config/picom.conf`
#################################
#          Animations           #
#################################
# requires https://github.com/jonaburg/picom
# (These are also the default values)
# transition-length = 600
# transition-pow-x = 0.1
# transition-pow-y = 0.1
# transition-pow-w = 0.1
# transition-pow-h = 0.1
# size-transition = true

# Shadow
shadow = true;
detect-rounded-corners = false;
shadow-radius = 50;
shadow-offset-x = -45;
shadow-offset-y = -45;
shadow-opacity = 0.45;
shadow-exclude = [
	"name = 'Notification'",
   "window_type = 'dock'",
	 "window_type = 'dialog'",
	 #"window_type = 'menu'",
	 #"window_type = 'dropdown_menu'",
	 #"window_type = 'popup_menu'", #start-menu and r-click men
	 "window_type = 'tooltip'",
	 "window_type = 'dialog'",
	 "window_type = 'splash'",
	 "window_type = 'utility'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'slop'",
  "class_g = 'Firefox' && argb",
  # "class_g *?= 'rofi'",
	"class_g = 'awesome'",
];

blur: {
  method = "dual_kawase";
  strength = 5.0;
  # kernel = "11x11gaussian";
   #background = false;
  #background-frame = false;
  # background-fixed = false
}

blur-background-exclude = [
	 #"window_type = 'dock'",
	 #"window_type = 'desktop'",
	 #"window_type = 'utility'",
	 #"window_type = 'dialog'",
	 #"window_type = 'popup_menu'", #start_menu
	 #"window_type = 'menu'",
	 #"window_type = 'dropdown_menu'",
	 #"window_type = 'tooltip'",
	 #"window_type = 'splash'",
	#"class_g = 'slop'",
	#"_GTK_FRAME_EXTENTS@:c"
];

corner-radius = 0;
round-borders = 1;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'panel'",
	"window_type = 'popup_menu'",
  "class_g *?= 'rofi'",
  "window_type = 'tooltip'",
   "class_g *?= 'dead-notification-center'"
];
opacity-rule = [#"window_type = 'dropdown_menu'",
  "90:class_g = 'Xfce4-power-manager-settings'",
  "92:class_g *?= 'chromium'",
  "90:class_g *?= 'spotify'",
  "100:class_g *?= 'vscodium'",
  "95:class_g *?= 'bitwarden'",
  "75:class_g = 'xob'",
  "98:class_g *?= 'qutebrowser'",
  "90:window_type = 'tooltip'",
  #"90:window_type = 'menu'",
  "87:window_type = 'popup_menu'",
  "87:window_type = 'dialog'",
  "87:window_type = 'splash'",
  "87:window_type = 'toolbar'",
  "87:window_type = 'utility'",
  "87:window_type = 'dock'",
	"60:window_type = 'dropdown_menu'",
  "85:window_type *?= '[Ss]xiv'"
];

# Fading
fading = true;
fade-delta = 5;
fade-in-step = 0.028;
fade-out-step = 0.03;
no-fading-openclose = false;

# fade-exclude = [
#   "class_g != 'bspc'"
# ];

# Other
# picom --experimental-backends --backend glx
experimental-backends = true;# no sense mofo
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
# use-ewmh-active-win = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;

focus-exclude = [
  "class_g = 'Cairo-clock'",
  "class_g ?= 'slop'",
  "name = 'rofi'",
  "class_g ?= 'Steam'"
];

# Logs
# log-level = "ERROR";
# log-file = "~/.cache/picom-log.log";

glx-no-stencil = true;
# glx-no-rebind-pixmap = true;
# xrender-sync-fence = true;
use-damage = true;
```

### Steps of reproduction
1. right mouse click on windows header or panel

### Expected behavior
no frame
### Current Behavior
it is frame
### Other details

![bug_frame___Screenshot_2020-12-18_22-06-16](https://user-images.githubusercontent.com/14309871/102657121-cbbfe380-417d-11eb-8843-02550d8855b2.png)

![bug_Screenshot_2020-12-18_22-18-28](https://user-images.githubusercontent.com/14309871/102657924-37ef1700-417f-11eb-8809-5ef276790c87.png)

**Comment by tryone144** [comment] 2020-12-18 20:42
Duplicate of https://github.com/yshui/picom/issues/552.

Possible workarounds:
1) Use a different GTK Theme without client side rendered shadows
2) Hack the theme yourself to disable the client side shadows
3) Disable background bluring using something along these lines in your config:
```
blur-background-exclude = [
  "window_type = 'menu'";
  "window_type = 'dropdown_menu'";
  "window_type = 'popup_menu'";
  "window_type = 'tooltip'";
];
```
or by using the `blur-background = false` option in the `wintypes` section.

We currently can't restrict the blurred region to only the semantically visible window because the whole area you see is the actual window. Would you mind posting the output of `xprop` for one of those windows if possible?

**Comment by yshui** [comment] 2020-12-18 22:45
I wonder if the menu window sets its Shape.

**Comment by tryone144** [comment] 2020-12-18 23:32
IIRC I read in a google result there should be a property with `_GTK` prefix indicating the actual window region similar to `_NET_FRAME_EXTENTS`.

Update: It seems it's called `GTK_FRAME_EXTENTS`. [Here](https://phabricator.kde.org/D24660) is the PR from kwin. However, I might have "hacked" my system to the point where all my GTK apps don't exhibit this property so I can't verify this right now.

**Comment by yshui** [comment] 2020-12-19 04:39
@tryone144 what does `xwininfo -shape` say?

**Comment by tryone144** [comment] 2020-12-19 11:02
> @tryone144 what does `xwininfo -shape` say?

```
  No window shape defined
  No border shape defined
```
But I also don't see the behaviour mentioned above. I'll have to get a new isolated setup up for testing this.

**Comment by tryone144** [comment] 2020-12-19 13:10
FYI, I've checked with xfce4 and they seem to set a window shape on the parent wm-window (for both CSD windows and "normal" ones). Probably due to the default theme having rounded titlebars?

We should be able to take `_GTK_FRAME_EXTENTS` to calculate the visible window rect and use that. Should help with the original issue, except for the rounded corners.

**Comment by Ygarr** [comment] 2020-12-20 23:53
So far, relatively the best option that I have achieved is just by making transparent(without blur) of problematic windows
with 
```
blur-background-exclude = [
....
"_GTK_FRAME_EXTENTS@:c"
];
```

![Screenshot_2020-12-21_01-52-31](https://user-images.githubusercontent.com/14309871/102727616-44b26d00-432f-11eb-9198-ed24a533b009.png)

**Comment by Ygarr** [comment] 2020-12-21 00:15
I fixed blurred frame (but blur remains inside window) for windows right-click menu on panel.
BUT windows 
 right-click on desktop and right-click on windows header STILL have frames.
 
 This does the hack-trick:
```
cat  ~/.config/gtk-3.0/gtk.css
.window-frame {box-shadow: none;
                margin: 0}

.titlebar {
  border-radius: 0;
  box-shadow: none;
                margin: 0
}
```
![Screenshot_2020-12-21_02-14-41](https://user-images.githubusercontent.com/14309871/102728086-6bbe6e00-4332-11eb-86d6-b860e6ca0ea7.png)

**Comment by Ygarr** [comment] 2020-12-21 00:23
and seems this in gtk.css do the rest
```
decoration
{
    border-radius: 6px 6px 0 0;
    border-width: 0px;
    /*box-shadow: 1px 12px 12px 12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(0, 0, 0, 0.18);*/
    box-shadow: none;
    margin: 4px;
}

decoration:backdrop
{
    border-radius: 6px 6px 0 0;
    border-width: 0px;
    /*box-shadow: 1px 12px 12px 12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(0, 0, 0, 0.18);*/
    box-shadow: none;
    margin: 4px;
}
.window-frame:backdrop {box-shadow: none;}
```

**Comment by tryone144** [comment] 2020-12-22 11:39
> `~/.config/gtk-3.0/gtk.css`

@Ygarr I found something similar on my system. This seems to be the "hack" to get rid of client-side shadows. :+1:
This should work for all gtk windows except for the stupid firefox menues with their arrow.

[GTK Inspector](https://wiki.gnome.org/action/show/Projects/GTK/Inspector) seems to be a good tool to check what rules have to be changed. I think this issue is a good candidate for a new wiki entry.

**Comment by ahmubashshir** [comment] 2021-08-21 09:07
> And seems this in gtk.css does the rest and exhausts the problem
> 
> ```
> decoration
> {
>     border-radius: 6px 6px 0 0;
>     border-width: 0px;
>     /*box-shadow: 1px 12px 12px 12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(0, 0, 0, 0.18);*/
>     box-shadow: none;
>     margin: 4px;
> }
> 
> decoration:backdrop
> {
>     border-radius: 6px 6px 0 0;
>     border-width: 0px;
>     /*box-shadow: 1px 12px 12px 12px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(0, 0, 0, 0.18);*/
>     box-shadow: none;
>     margin: 4px;
> }
> .window-frame:backdrop {box-shadow: none;}
> 
> tooltip {
>   /*color: #4a4a4a;*/
>   border-radius: 0px;
>   border: 0px solid #d0d0d0; 
>   box-shadow: none;
>     margin: 1px;}
> tooltip.background {
>     /*background-color: #6c92d7;*/
>     background-clip:padding-box;
>     box-shadow: none;
>     margin: 1px; }
> tooltip.background label {
>       padding: 0px;
>       box-shadow: none;
>     margin: 0px;}
> }
> ```

Doesn't work with Gtk4.

**Comment by HugLifeTiZ** [comment] 2021-09-03 21:54
It *kind of* works in GTK4, but it seems that even if you take away every reason GTK4 would want to hold that space, it still insists on having 12-pixel extents on all sides as resize handles. I can see why they would do that, honestly, as someone who used this hack on GTK3 and sometimes forgets to do Super+RClick for resizing.

As far as I can tell, the only way around it is not using GTK4 apps until Picom does something smart with _GTK_FRAME_EXTENTS. I imagine only GNOME apps will be in a hurry to migrate to GTK4. Wayland was the big thing that spurred people on to GTK3, but in GTK4, GNOME is pushing ideology much harder. There's no big looming reason to migrate to GTK4, fortunately.

**Comment by cervyesterday** [comment] 2021-09-09 19:27
Hi,
I had the same problem in Manjaro Kde with i3 as wm. I noticed that this problem occoured choosing kvantum in the applicaton style settings section, while using Breeze (the default gtk theme in kde) everything was fine.
I fixed modifying the config file of the theme in kvantum:
Go to .config/Kvantum/folder of the theme you want to change/themename.kvconfig; you'll find a line with:
`shadowless_popup=false
`, just change it in `shadowless_popup=true
`
Hope everything is clear

**Comment by arm332** [comment] 2022-07-21 20:01
A simple workaround that I'm using is this  ~/.config/gtk-4.0/gtk.css to disable rounded corners and shadows for GTK4 menus.

popover contents {
	border-bottom-left-radius: 0;
	border-bottom-right-radius: 0;
	border-top-left-radius: 0;
	border-top-right-radius: 0;
	box-shadow: none;
}

Also, from picom.conf, it is possible to remove "class_g = 'Firefox' && argb" and "class_g = 'thunderbird' && argb" from "shadow-exclude".

**Comment by yshui** [comment] 2022-07-21 21:00
I think this issue is adequately resolved.

**Closed by yshui** 2022-07-21 21:00 UTC
Labels: duplicate
