### ISSUE TITLE
--frame-opacity with --experimental-backends causes flickering, completely unusable

### ISSUE THREAD

**Issue by Admicos** [yshui/picom#303] opened 2020-01-21 07:18 UTC
### Platform
Gentoo (fully up-to-date, with GentooLTO patches)

### GPU, drivers, and screen setup
```
% eix -I xf86-video --compact
[I] x11-drivers/xf86-video-amdgpu (19.1.0@01/16/2020): Accelerated Open Source driver for AMDGPU cards
[I] x11-drivers/xf86-video-ati (19.1.0@01/16/2020): ATI video driver

% glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.11-ck, LLVM 9.0.1) (0x67df)
    Version: 19.3.2
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 8013 MB, largest block: 8013 MB
    VBO free aux. memory - total: 8142 MB, largest block: 8142 MB
    Texture free memory - total: 8013 MB, largest block: 8013 MB
    Texture free aux. memory - total: 8142 MB, largest block: 8142 MB
    Renderbuffer free memory - total: 8013 MB, largest block: 8013 MB
    Renderbuffer free aux. memory - total: 8142 MB, largest block: 8142 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16384 MB
    Currently available dedicated video memory: 8013 MB
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.11-ck, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

% xrandr
Screen 0: minimum 320 x 200, current 3286 x 1080, maximum 16384 x 16384
DisplayPort-0 disconnected primary (normal left inverted right x axis y axis)
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
HDMI-A-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 476mm x 268mm
   1920x1080     60.00*+  50.00    59.94
   1680x1050     59.88
   1600x900      60.00
   1280x1024     75.02    60.02
   1440x900      60.00
   1280x800      59.91
   1152x864      75.00
   1280x720      60.00    50.00    59.94
   1024x768      75.03    60.00
   832x624       74.55
   800x600       75.00    60.32
   720x576       50.00
   720x480       60.00    59.94
   640x480       75.00    60.00    59.94
   720x400       70.08
HDMI-A-1 connected 1366x768+1920+0 (normal left inverted right x axis y axis) 413mm x 234mm
   1366x768      59.79*+
   1920x1080     60.00    59.94
   1360x768      60.02
   1280x720      60.00    59.94
   1024x768      75.03    72.00    70.07    60.00
   832x624       74.55
   800x600       72.19    75.00    60.32    56.25
   720x480       60.00    59.94
   640x480       75.00    72.81    66.67    60.00    59.94
   720x400       70.08
DVI-D-0 disconnected (normal left inverted right x axis y axis)
```

### Environment
bspwm 0.9.9, no patches, nothing special

### picom version
```
% picom --version
vgit-b0267

% picom --diagnostics
[ 01/21/2020 10:07:10.179 init_render WARN ] Old backends only support blur method "kernel". Your blur setting will not be applied
**Version:** vgit-b0267

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/admicos/.config/picom.conf

### Drivers (inaccurate):

AMDGPU, Radeon
```

### Configuration:
```
picom --experimental-backends --config /dev/null --backend glx --shadow --blur-method gaussian --blur-size 10 --blur-background --fading --mark-wmwin-focused --mark-ovredir-focused --detect-rounded-corners --detect-client-opacity --unredir-if-possible --detect-transient --detect-client-leader --glx-no-stencil --glx-no-rebind-pixmap --shadow-radius 7 --shadow-offset-x -7 --shadow-offset-y -7 --frame-opacity 0.7 --log-level debug
```

I was just copying from my config onto the command line to isolate the bug, most of these won't be needed

More minimal configuration: `picom --experimental-backends --config /dev/null --frame-opacity 0.7 --backend glx`

### Steps of reproduction

1. Run the commands in the configuration section to observe bug
2. Remove `--frame-opacity 0.7` and re-run for everything to work normally

### Expected behavior
Everything should worked well

### Current Behavior
Both monitors flash with "garbage" data (mostly green with random rectangles of screen data), console spammed with the following line:

```
[ 01/21/2020 10:12:20.077 _gl_compose ERROR ] GLX error at line 438: GL_INVALID_OPERATION
[ 01/21/2020 10:12:20.091 _gl_compose ERROR ] GLX error at line 438: GL_INVALID_OPERATION
...
```

### Stack trace
N/A

### Other details
Video recording: https://files.ecmelberk.com/picom-issue-303.mp4

**Comment by mighty9245** [comment] 2020-01-27 05:51
frame opacity seems to be completely broken, see last comments in #212

**Comment by yshui** [comment] 2020-02-07 13:55
Can you run picom with apitrace and attach the trace here? thanks.

**Comment by yshui** [comment] 2020-03-07 19:52
@Admicos sorry but the link to your video is broken

**Comment by yshui** [comment] 2020-03-07 19:53
I couldn't reproduce this bug locally.

**Comment by Vladimir-csp** [comment] 2020-03-12 06:17
I can confirm this. If frame-opacity < 1, after some time picom stops refreshing the screen and those messages are spammed in console:
```
[ 2020-03-12 09:04:17.602 _gl_compose ERROR ] GLX error at line 438: GL_INVALID_OPERATION
[ 2020-03-12 09:04:17.603 gl_blur ERROR ] GLX error at line 727: GL_INVALID_OPERATION
[ 2020-03-12 09:04:17.616 glx_bind_pixmap ERROR ] GLX error at line 452: GL_INVALID_OPERATION
```
I have to move and switch windows a bit to trigger it.

Also frames are completely opaque even if frame-opacity is set to 0.1.

Openbox 3.6.1, Mesa 19.3.3, Intel(R) HD Graphics 520 (Skylake GT2)

[picom.trace.gz](https://github.com/yshui/picom/files/4322574/picom.trace.gz)

**Comment by yshui** [comment] 2020-03-12 09:58
@Vladimir-csp thanks for the trace.

**Comment by yshui** [comment] 2020-03-17 19:56
@Admicos Can you try the latest `next`? might have been fixed now.

**Comment by Admicos** [comment] 2020-03-17 20:04
Seems to work fine now!

(sorry for not being that active here, I saw the notification mails come in, but always had something else to do)

(also my domain the video was on expired recently, that was why it wasn't working, edited the OP with a newer link, though it's probably not any use at it seems to be fixed)

**Closed** 2020-03-17 20:06 UTC
Labels: artifacts, not reproduced
