### ISSUE TITLE
Picom segfaults when xfce4-terminal force closed as root

### ISSUE THREAD

**Issue by arabcian** [yshui/picom#425] opened 2020-06-01 17:06 UTC
### Platform

Gentoo linux 17.1
### GPU, drivers, and screen setup

intel uhd 630
### Environment

fluxbox
### picom version

8.0
### Configuration:
```
// Paste your configuration here
```

### Steps of reproduction

1.open a xfce4-terminal type su then enter password and close the window
2.

### Expected behavior
not to crash
### Current Behavior
it dies
### Stack trace

picom --experimental-backends --backend glx --use-damage --glx-no-rebind-pixmap --glx-no-stencil --unredir-if-possible --vsync
[ 06/01/2020 19:57:16.695 win_clear_flags WARN ] Flags cleared on a destroyed window 0x01c631ca (Terminal - root@tux:/home/cian)
[ 06/01/2020 19:57:16.695 win_clear_flags WARN ] Flags cleared on a destroyed window 0x01c631ca (Terminal - root@tux:/home/cian)
picom: ../picom-8/src/backend/backend.c:270: paint_all_new: Assertion `!(w->flags & WIN_FLAGS_SHADOW_NONE)' failed.
Aborted

**Comment by arabcian** [comment] 2020-06-01 17:09
Hello im forced to use --experimental-backends because standart backends cause tearing and artifacts

**Comment by mighty9245** [comment] 2020-06-02 12:20
possible dup #393, #394, #396 and others

there is no problem that you're using experimental backends. they're supposed to replace the old ones when they'll be stable enough.

**Comment by botiapa** [comment] 2020-08-07 15:20
Is there a workaround for this? It's quite annoying.

**Comment by tryone144** [comment] 2020-09-08 14:08
I think I've found a fix/workaround for issue https://github.com/yshui/picom/issues/394 which is most likely a duplicate of this one. However I can't reproduce this specific case on my system.

Can you try if [this PR](https://github.com/tryone144/picom/tree/fix/clear-shadow-stale-on-unmap) https://github.com/yshui/picom/pull/479 also fixes the assertion failure for you?

**Comment by tryone144** [comment] 2020-12-15 16:57
Should be fixed in v8.2.
Be sure to leave a comment here if this still happens for you.

**Closed by tryone144** 2020-12-15 16:57 UTC
