### ISSUE TITLE
Random picom crash

### ISSUE THREAD

**Issue by toomuchsalt** [yshui/picom#542] opened 2020-11-13 14:46 UTC
### Platform
Ubuntu 20.10

### GPU, drivers, and screen setup
NVidia GTX 2070, nvidia-drivers 450.80.02, one monitor, 2560x1440@144
[packages.log](https://github.com/yshui/picom/files/5537386/packages.log)
[glxinfo.log](https://github.com/yshui/picom/files/5537367/glxinfo.log)

### Environment
xfce-desktop
kernel Linux 5.8.0-26-generic

### picom version
```
➤ picom --version
vgit-248bf
➤ picom --diagnostics
**Version:** vgit-248bf

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes
* Config file used: /home/vplazun/.config/picom/picom.conf

### Drivers (inaccurate):

NVIDIA
```

### Configuration:
```
#################################
#             Shadows           #
#################################

shadow = true;

shadow-radius = 7;

shadow-offset-x = -7;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Firefox' && !window_type *= 'menu'",
  "class_g = 'Nightly' && !window_type *= 'menu'"
];

#################################
#           Fading              #
#################################

fading = true
fade-in-step = 0.1;
fade-out-step = 0.1;

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 1.0;

frame-opacity = 1.0;
inactive-opacity-override = false;
inactive-dim = 0.1
focus-exclude = [ "class_g = 'Cairo-clock'" ];
blur-kern = "";
# blur-kern = "3x3box";

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

backend = "glx";
vsync = true
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0
detect-transient = true
detect-client-leader = true
glx-no-stencil = true
glx-no-rebind-pixmap = true
use-damage = true
xrender-sync-fence = false
log-level = "warn";

log-file = "*HOME*/.picom.log";

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 1.0; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1.0; shadow = false; }
  dropdown_menu = { opacity = 1.0; shadow = false; }
};
```

### Steps of reproduction
Not sure, it just crashes occasionally when unlocking desktop, using Clion or anything else

### Current Behavior
Crash when switching widnows or unlocking desktop

### Stack trace
[core.tar.gz](https://github.com/yshui/picom/files/5537436/core.tar.gz)

**Comment by tryone144** [comment] 2020-11-13 15:05
Assertion fails in `win_on_win_size_change()` for a window in state `WSTATE_UNMAPPING`. Duplicate of #525.

**Comment by BachoSeven** [comment] 2020-11-29 22:30
The aforementioned #525 was closed just yesterday, so I think this can be closed as well.

**Comment by yshui** [comment] 2020-11-29 23:36
@BachoSeven Thanks.

@toomuchsalt if this still happens after you upgrade, be sure to leave a comment here

**Closed by yshui** 2020-11-29 23:36 UTC
Labels: duplicate
