### ISSUE TITLE
Shadows left behind when window resized

### ISSUE THREAD

**Issue by sersorrel** [yshui/picom#555] opened 2020-12-02 13:20 UTC
### Platform
Ubuntu Desktop 18.04 amd64

### GPU, drivers, and screen setup

nvidia gtx 1050, nvidia-drivers 455.45, two monitors with xrandr
```console
$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 4096 MB
    Currently available dedicated video memory: 3039 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1050/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 455.45.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 455.45.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 455.45.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### Environment

i3wm 4.19

### picom version

vgit-685e5, or vgit-a56d6, or vgit-bb54d

### Configuration:
```
backend = "glx";
# backend = "xr_glx_hybrid";

vsync = true;

# Attempt to unredirect when a fullscreen window is detected for improved performance.
# unredir-if-possible = true;
# Don't unredirect windows that asked for compositing.
unredir-if-possible-exclude = [
	"_NET_WM_BYPASS_COMPOSITOR@:c = 2",
	"class_g = 'Totem'"
];

shadow = true;
# https://github.com/chjj/compton/issues/408
shadow-exclude = [
	"class_g = 'i3-frame'",
	"class_g = 'i3bar'",
	# don't draw shadows for hidden windows (e.g. those in other tabs), but only if they're not floating
	# the update-notifier window is always "hidden", even when it's visible, so this hack is required
	# "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
	# originally:
	# "_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_HIDDEN' && !I3_FLOATING_WINDOW@:c = 1",
	# "_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_HIDDEN' && !I3_FLOATING_WINDOW@:c = 1",
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN' && !I3_FLOATING_WINDOW@:c = 1"
	# "_GTK_FRAME_EXTENTS@:c", # avoid double shadows on some windows?
];
# shadow-exclude-reg = "x31+0-0"; # don't draw shadows under i3bar
xinerama-shadow-crop = true; # don't draw shadows across displays

# Step the fade every 5ms.
fade-delta = 5;
# Only fade certain windows.
wintypes:
{
	tooltip = { fade = true; };
	notify = { fade = true; };
}

# resize-damage = 12;
```

### Steps of reproduction

1. Open a nautilus window
2. Open a totem window and place it on top of the nautilus window
3. Resize totem

### Expected behavior
Shadowed areas of nautilus should be redrawn when no longer in shadow

### Current Behavior
Resizing totem (or some other applications) leaves behind visual artifacts when on top of nautilus windows. Increasing resize-damage makes the issue a little less prominent (though still leaves artifacts if the window is resized by a long distance in a single frame).

### Other details

![image](https://user-images.githubusercontent.com/9433472/100877544-d4879880-34a0-11eb-8324-2055241d0f25.png)

**Comment by yshui** [comment] 2020-12-03 06:12
This only happens on top of nautilus windows?

**Comment by yshui** [comment] 2020-12-03 06:17
I tried totem on top of nautilus, but I cannot reproduce this problem.

**Comment by yshui** [comment] 2020-12-03 06:59
Are you using `--experimental-backends`, BTW?

**Comment by sersorrel** [comment] 2020-12-03 13:54
I originally noticed it with nautilus+totem – on further testing it also happens for me with evince, baobab, and gnome-system-monitor (and presumably other GTK apps).

It happens when any affected app is on the bottom, but only when nautilus, evince, or totem (not g-s-m or baobab) is the window being resized; the first three apps have thick window headers (client-side decorations), but g-s-m and baobab do not, I guess that might be related?

I'm not using `--experimental-backends`, and enabling it doesn't help.

**Comment by yshui** [comment] 2020-12-03 23:57
Yes, I can reproduce it now, although I am using different applications. I believe it is the same issue as yours.

**Comment by yshui** [comment] 2020-12-04 01:14
Can you update to the latest `next` branch, then [capture a apitrace](https://github.com/yshui/picom/wiki/Reporting-issues#capture-a-trace)? You need to also enable trace logging: `--log-level=trace`

**Comment by sersorrel** [comment] 2020-12-05 00:06
With latest `next` I can no longer reproduce this – it seems like you did fix it :)

**Comment by yshui** [comment] 2020-12-05 08:15
OK, I will close this then.

**Closed by yshui** 2020-12-05 08:15 UTC
Labels: bug, not reproduced
