### ISSUE TITLE
We seems to have run of XIDs. This is  X server, or a resource leakage in the compositor.

### ISSUE THREAD

**Issue by fengwk** [yshui/picom#885] opened 2022-09-01 15:56 UTC
### Platform

```
                   -`                    fengwk@arch
                  .o+`                   -----------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: Prestige 15 A10SC REV:1.0
               `+oooooo:                 Kernel: 5.19.5-arch1-1
               -+oooooo+:                Uptime: 32 mins
             `/:-:++oooo+:               Packages: 643 (pacman)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 3840x2160, 3840x2160
          `/+++ooooooooooooo/`           WM: dwm
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.        Terminal: st
      :osssssss/        osssso+++.       Terminal Font: SauceCodePro Nerd Font Mono
     /ossssssss/        +ssssooo/-       CPU: Intel i7-10710U (12) @ 4.700GHz
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
  `+sso+:-`                 `.-/+oso:    GPU: Intel Comet Lake UHD Graphics
 `++:.                           `-/+/   Memory: 2455MiB / 31938MiB
 .`                                 `/
```

### GPU, drivers, and screen setup

Single screen and double screen can be reproduced

### Environment

dwm

### picom version

picom 9.1-3

### Configuration:

no configuration, just run `picom -b`

### Steps of reproduction

Use screenshot software to take screenshots. software like:

- flameshot
- popo's screenshot

### Expected behavior

picom won't clash

### Current Behavior

picom clashed

### Stack trace

```
[ 09/01/22 23:55:47.498 x_new_id FATAL ERROR ] We seems to have run of XIDs. This is either a bug in the X server, or a resource leakage in the compositor. Please open
an issue about this problem. The compositor will die.
zsh: IOT instruction (core dumped)  picom
```

**Comment by yshui** [comment] 2022-09-01 22:07
Duplicate of #255 

You can use `--experimental-backends`, or use the latest git version.

**Closed by yshui** 2022-09-01 22:07 UTC

**Comment by fengwk** [comment] 2022-09-27 17:37
> Duplicate of #255 
> 
> You can use `--experimental-backends`, or use the latest git version.

its resolved
