### ISSUE TITLE
Feature/Question: Fade on Destroy

### ISSUE THREAD

**Issue by pijulius** [yshui/picom#704] opened 2021-10-04 17:01 UTC
Hi Guys,

I know we have the fade-out option when unmapping windows and that works perfectly fine. The questions I would have is that would it be possible to do the same when destroying windows too?

Played around a bit and was able to make it happen but unfortunately it's not 100% accurate, sometimes it does fade but most of the times it doesn't. I imagine it's because window in reality isn't there anymore but we do have the image of it, wouldn't it be possible to animate that static image in this case?

What I did for quick testing is simply replace destroy_win_start() content with unmap_win_start() and when WSTATE_UNMAPPED continue with the destroy.

What do you think guys? would this be possible at all or is the reason for not working 100% because X simply clears the window and there isn't anything we can do about it because we can't just animate a picture on the server without having the window?

Thank you in advance!

**Comment by pijulius** [comment] 2021-10-19 08:21
Ok, found the solution.

The solution is in picom.c itself, when a window is unmapped it will set the to_paint to false and so the fading will never happen because it isn't painted.

A simple if like this:
	if (!*fade_running || w->opacity == w->opacity_target)
		to_paint = false;

fixes this and so now fading out will animate even when closing windows.
A commit can be seen in my fork but please note that also includes the animations implemented by Daniel.

https://github.com/pijulius/picom/commit/7b674f9bdbf2916d80de5cfda783e820409904ee

Please let me know if you wish to make a pull request on this or if at all this is something you would want to commit to the original picom.

**Comment by Exordio** [comment] 2023-06-13 02:18
bug is still here...

**Comment by Onred** [comment] 2023-08-02 06:35
Any progress on this? This issue is pretty much the last bit of jank I need to work out of my system for it to be beautiful.

**Comment by Exordio** [comment] 2023-08-02 08:48
> Any progress on this? This issue is pretty much the last bit of jank I need to work out of my system for it to be beautiful.

if you want it to be good, use kwin. He can do the same.

**Comment by allusive-dev** [comment] 2023-10-29 09:03
> Ok, found the solution.
> 
> The solution is in picom.c itself, when a window is unmapped it will set the to_paint to false and so the fading will never happen because it isn't painted.
> 
> A simple if like this: if (!*fade_running || w->opacity == w->opacity_target) to_paint = false;
> 
> fixes this and so now fading out will animate even when closing windows. A commit can be seen in my fork but please note that also includes the animations implemented by Daniel.
> 
> [pijulius@7b674f9](https://github.com/pijulius/picom/commit/7b674f9bdbf2916d80de5cfda783e820409904ee)
> 
> Please let me know if you wish to make a pull request on this or if at all this is something you would want to commit to the original picom.

This issue is still present.

I am working on updating my fork of pijulius picom to yshui's picom `v10.2`.
So far everything is working with almost zero issues however, windows neither fade out nor have a unmap animation. 

I have spent over 10 hours analyzing all the code side by side with meld and confirming that there are no key differences that are causing this.

No obvious errors are outputted when running picom and I checked that it wasn't an issue reading the config by creating a runtime argument which manually sets the unmap animation.

The line that pijulius mentioned as fixing the issue has not resolved it for me and from the looks of the recent comments it hasn't resolved it for others either.

[Here](https://github.com/allusive-dev/picom-allusive/tree/unstable) is the repository if either of you are interested.

**Comment by allusive-dev** [comment] 2023-10-30 04:07
Hello Again Everyone.

I have come back to let everyone know that I have resolved the issue.

I believe the issue was being caused by that in `yshui/picom` fade steps is a `long long` but in mine it is just `long`.
Aswell as a few other small things that could have resolved this. 
I also noticed that unmap animations actually do not render if you have `fading = false;`

With that out of the way... Picom Allusive v1.0.0 will be releasing within 10 minutes of this comment.
I don't want to just completely self promote here so if you are interested please check out [picom-allusive here](https://github.com/allusive-dev/picom-allusive)

**Comment by yshui** [comment] 2024-01-20 13:30
hey, sorry for neglecting this.

I tried several simple apps (xev, xclock, xeyes, gedit, etc.) under awesomeWM and they all fade correctly when closed.

what's the app and WM combination that have this problem?

**Comment by ghost** [comment] 2024-01-20 22:28
> I believe the issue was being caused by that in `yshui/picom` fade steps is a `long long` but in Compfy it is just `long`.

@yshui I think that this is the cause of the issue or at least related.

**Comment by DarioDarko** [comment] 2024-01-21 15:41
i am using endeavourOS with openbox.

i tested alacritty, xev, pcmanfm, librewolf and nitrogen. theres little to no difference between these programs, only alacritty for some reason shows the animation more often. the fadeout is way more likely to happen, if theres only 1 window on the (virtual) desktop. as soon as theres 2+ windows on the desktop theyll fadeout very, very rarely.

this also affects animations of closing a window on all picom forks ive tested, besides picom-allusive/compfy. so at least for my setup i can confirm that jaspers fix solved the issue 100%. i was running his fork for the last couple of months without a single occurance of the problem.

if you need more information/testing from my side let me know.

**Comment by yshui** [comment] 2024-01-21 16:19
> > I believe the issue was being caused by that in `yshui/picom` fade steps is a `long long` but in Compfy it is just `long`.
> 
> @yshui I think that this is the cause of the issue or at least related.

hmm, interesting. so maybe the steps underflowed, or otherwise got corrupted somewhere and became a huge number? a wild guess.

**Comment by absolutelynothelix** [comment] 2024-01-21 16:49
are there any warnings from picom when closing a window?

**Comment by yshui** [comment] 2024-01-21 17:16
OK, I've found the root cause.

@jasper-at-windswept it has absolutely nothing to do with `long` vs `long long`.

openbox destroys the client window before its frame window. When the client window is destroyed, we detach it from the frame window, now the frame window has `client_win == 0`. this unfortunately means it becomes equal to `ps->debug_window` when debug mode is not used. so this condition is hit:

https://github.com/yshui/picom/blob/197b4bd396590cb5df61eb54ec6a1dadf1115a5d/src/picom.c#L978

compfy doesn't have this problem because it added an extra condition in that branch:

https://github.com/allusive-dev/compfy/blob/b92d8b18771700a001f07de3a2f8748d91447c3b/src/compfy.c#L967

**Comment by yshui** [comment] 2024-01-21 17:29
Should be fixed in `next`

**Closed** 2024-01-21 17:28 UTC

**Comment by ghost** [comment] 2024-01-21 20:41
> compfy doesn't have this problem because it added an extra condition in that branch:
> https://github.com/allusive-dev/compfy/blob/b92d8b18771700a001f07de3a2f8748d91447c3b/src/compfy.c#L967

Ah alright. Glad you figured it out!
