### ISSUE TITLE
[Feature/Pull request] Add BlackCapCoder's window animation code.

### ISSUE THREAD

**Issue by SkyyySi** [yshui/picom#420] opened 2020-05-27 12:02 UTC
First up, I didn't open a pull request because Github doesn't recognize them as "compatible" forks, so I'll do it here instead.
The one big thing missing from compton/picom is, in my opinion, window animations. However, BlackCapCoder actually implemented them already, but only for tiling window managers. The animations still work on floating wms, but they don't affect minimizing (because that's not a thing so tiling wms duh) but the ones that DO work work great (tested on Openbox and i3-gaps).
I'd love to see you implement them :)

**Comment by wokawoka** [comment] 2020-06-05 15:24
it would be great indeed. I'm praying for it

**Comment by sandsmark** [comment] 2020-06-25 16:07
https://github.com/sandsmark/picom/commit/51fdb8bcaafc4e1261a644873358031c37e09f83 here's BlackCapCoder's implementation rebased on top of picom.

It's a bit of a mess, so probably easier to just reimplement from scratch (I haven't tested it, and some code I didn't find out how to port).

**Comment by absolutelynothelix** [comment] 2023-09-02 12:39
closing as duplicate of #1121.

**Closed by absolutelynothelix** 2023-09-02 12:39 UTC
