### ISSUE TITLE
Some windows are not displayed after reloading i3

### ISSUE THREAD

**Issue by link1375** [yshui/picom#166] opened 2019-05-02 09:55 UTC
Hi,

I am using arch with i3 and wanted to apply blur in combination with transparency. Everything works fine, but if I reload i3 (mod+Shift+r) windows are not properly displayed anymore. The same occurs with the normal compton package. To test if this a general problem for my configuration I installed xcompmgr and there is no problem. Also compton outputs a lot of Bad Window erros. After killing the compton process all windows are displayed but obviously without transparency. Starting the process again leads to the same problem.
I could not determine which applications are affected since e.g. firefox is displayed on one workspace but not on another.
As suggested by https://github.com/tryone144/compton/issues/11#issuecomment-488401384 killing compton, reloading i3 and restarting compton does work.

![photo_2019-05-01_20-08-43](https://user-images.githubusercontent.com/33375235/57068065-f6230b80-6cd0-11e9-89b9-9681e4336bce.jpg)
![photo_2019-05-01_20-08-51](https://user-images.githubusercontent.com/33375235/57068071-fa4f2900-6cd0-11e9-8b34-03ec481173dc.jpg)

**Comment by yshui** [comment] 2019-05-02 12:55
Might be the same bug as #134

**Comment by link1375** [comment] 2019-05-02 16:37
Maybe, but I don't have problems with sleep/wake up. Multihead did I not test yet.

**Comment by yshui** [comment] 2019-05-02 17:56
BTW, which version of compton are you using? Could you try building from the `next` branch and see if this problem still happens?

**Comment by link1375** [comment] 2019-05-03 11:41
Currentyl I am using [compton-tryone](https://github.com/tryone144/compton). I installed this and your version via AUR.

**Comment by morgoth6** [comment] 2019-05-06 07:25
I have similar problem using i3 some time ago. Additionally with flashing portions of already displayed windows and missing text in urxvt. No time to bisecting it now, but current next with reverted 4205ee5a85c658f02c67ce6a8c31f3ea3f525f4b seems to cure it for me.

**Comment by yshui** [comment] 2019-05-06 13:52
@morgoth6 Can you [capture a trace](https://github.com/yshui/compton/wiki/Reporting-an-issue#capture-a-trace)?

**Comment by morgoth6** [comment] 2019-05-17 08:08
> @morgoth6 Can you [capture a trace](https://github.com/yshui/compton/wiki/Reporting-an-issue#capture-a-trace)?

Sorry for delay. I can try, but is there a way to trigger trace at runtime ? (signal, hotkey ?) This problem does not appear always/immediately (to be more acurate it's hard to spot sometimes) and it may be hard to catch short capture. It seems to happen more frequently when URXVT with some tabs open and when Virt-viewer, but this can be contingency only.

For now today's build still works with this commit reverted. I will try with pure build in a moment.

**Comment by yshui** [comment] 2019-05-18 11:42
@morgoth6 
> but is there a way to trigger trace at runtime ?

This is not possible with apitrace.

BTW, if you are going to capture a trace, please remember to use `--log-level=trace` when doing that.

**Comment by tryone144** [comment] 2022-06-07 21:22
The workaround highly suggests this is indeed a duplicate of https://github.com/yshui/picom/issues/134.
If this can still be reproduced with the current next, feel free to re-open and provide more details.

**Closed by tryone144** 2022-06-07 21:22 UTC
Labels: bug, artifacts, info requested
